// Centralized icon components using Expo vector icons (Feather set, similar to Lucide)
import { Feather } from '@expo/vector-icons';
import React from 'react';
import SarcasticLaughIcon from './Icons/SarcasticLaughIcon';

export { SarcasticLaughIcon };

export const ClockIcon = (props) => <Feather name="clock" size={20} {...props} />;
export const BellIcon = (props) => <Feather name="bell" {...props} />;
export const BellOffIcon = (props) => <Feather name="bell-off" {...props} />;
export const PaletteIcon = (props) => <Feather name="droplet" {...props} />;
export const ShieldIcon = (props) => <Feather name="shield" {...props} />;
export const HelpCircleIcon = (props) => <Feather name="help-circle" {...props} />;
export const InfoIcon = (props) => <Feather name="info" {...props} />;
export const LogOutIcon = (props) => <Feather name="log-out" {...props} />;
export const BarChartIcon = (props) => <Feather name="bar-chart-2" size={20} {...props} />;
export const SettingsIcon = (props) => <Feather name="settings" size={20} {...props} />;
export const CrownIcon = (props) => <Feather name="award" size={16} {...props} />;
export const CheckIcon = (props) => <Feather name="check" size={18} {...props} />;
export const PlusIcon = (props) => <Feather name="plus" size={20} {...props} />;
export const TrashIcon = (props) => <Feather name="trash-2" size={18} {...props} />;
export const ChevronRightIcon = (props) => <Feather name="chevron-right" size={20} {...props} />;
export const AlertCircleIcon = (props) => <Feather name="alert-circle" size={20} {...props} />;
export const TargetIcon = (props) => <Feather name="target" size={20} {...props} />;
export const XIcon = (props) => <Feather name="x" size={20} {...props} />;
export const MusicIcon = (props) => <Feather name="music" size={18} {...props} />;
export const CameraIcon = (props) => <Feather name="camera" size={18} {...props} />;
export const MessageIcon = (props) => <Feather name="message-circle" size={18} {...props} />;
export const PlayIcon = (props) => <Feather name="play" size={18} {...props} />;
export const UserIcon = (props) => <Feather name="user" size={18} {...props} />;
export const ShoppingIcon = (props) => <Feather name="shopping-cart" size={18} {...props} />;
export const LinkedinIcon = (props) => <Feather name="linkedin" size={18} {...props} />;
export const MailIcon = (props) => <Feather name="mail" size={20} {...props} />;
export const LockIcon = (props) => <Feather name="lock" size={20} {...props} />;
export const EyeIcon = (props) => <Feather name="eye" size={20} {...props} />;
export const EyeOffIcon = (props) => <Feather name="eye-off" size={20} {...props} />;
export const AppleIcon = (props) => <Feather name="smartphone" size={20} {...props} />; // Using smartphone as fallback for Apple
export const ZapIcon = (props) => <Feather name="zap" size={20} {...props} />;
export const CloudIcon = (props) => <Feather name="cloud" size={20} {...props} />;
export const AlertTriangleIcon = (props) => <Feather name="alert-triangle" size={20} {...props} />;
export const RefreshCcwIcon = (props) => <Feather name="refresh-ccw" size={20} {...props} />;
export const AppsIcon = (props) => <Feather name="grid" size={20} {...props} />;
export const CalendarIcon = (props) => <Feather name="calendar" size={20} {...props} />;
export const CheckCircleIcon = (props) => <Feather name="check-circle" size={20} {...props} />;
export const DownloadIcon = (props) => <Feather name="download" size={20} {...props} />;
export const ExternalLinkIcon = (props) => <Feather name="external-link" size={20} {...props} />;
export const PieChartIcon = (props) => <Feather name="pie-chart" size={20} {...props} />;
export const SearchIcon = (props) => <Feather name="search" size={20} {...props} />;
export const ShareIcon = (props) => <Feather name="share-2" size={20} {...props} />;
export const TrendingUpIcon = (props) => <Feather name="trending-up" size={20} {...props} />;
export const BarChart3Icon = (props) => <Feather name="bar-chart-2" size={20} {...props} />;
