// Export utilities for analytics data

import * as FileSystem from 'expo-file-system';
import { computeSummary, computeMostBlockedApps, computeTimeSpentOnApps, formatHrsMins } from './analytics';

export async function exportAnalyticsAsCSV(history) {
  const summary = computeSummary(history);
  const topApps = computeMostBlockedApps(history, 10);
  const timeSpentApps = computeTimeSpentOnApps(history);
  
  // CSV Header
  let csv = 'Date,Start Time,Duration (minutes),Apps Blocked,Ended Early\n';
  
  // Session data
  history.forEach(session => {
    const date = new Date(session.startAt).toISOString().split('T')[0];
    const startTime = new Date(session.startAt).toLocaleTimeString();
    const duration = Math.round((session.durationSeconds || 0) / 60);
    const apps = (session.apps || []).join(';');
    const endedEarly = session.endedEarly ? 'Yes' : 'No';
    
    csv += `${date},${startTime},${duration},"${apps}",${endedEarly}\n`;
  });
  
  return csv;
}

export async function exportAnalyticsReport(history) {
  const summary = computeSummary(history);
  const topApps = computeMostBlockedApps(history, 5);
  const timeSpentApps = computeTimeSpentOnApps(history);
  
  const totalHours = Math.floor(summary.totalFocusSeconds / 3600);
  const totalMinutes = Math.round((summary.totalFocusSeconds % 3600) / 60);
  
  const report = `
FocusFlow Analytics Report
Generated: ${new Date().toLocaleDateString()}

=== SUMMARY ===
Total Sessions: ${summary.totalSessions}
Total Focus Time: ${totalHours}h ${totalMinutes}m
Average Session: ${Math.round(summary.avgSessionSeconds / 60)}m
Best Streak: ${summary.bestStreakDays} days
Weekly Change: ${summary.changeVsLastWeekPercent}%

=== TOP BLOCKED APPS ===
${topApps.map((app, i) => `${i + 1}. ${app.label}: ${app.count} times`).join('\n')}

=== TIME SAVED ===
${timeSpentApps.slice(0, 5).map((app, i) => {
  const { h, m } = app.timeFormatted;
  return `${i + 1}. ${app.label}: ${h}h ${m}m saved`;
}).join('\n')}

=== INSIGHTS ===
• Most productive day: ${['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][summary.productiveDayIndex]}
• Focus sessions help you avoid distractions and build better habits
• Keep up the great work building your focus muscle!

---
Generated by FocusFlow - Unbreakable Focus & Smart Reminders
`;

  return report.trim();
}

export async function shareAnalytics(history, format = 'report') {
  try {
    let content, filename, mimeType;
    
    if (format === 'csv') {
      content = await exportAnalyticsAsCSV(history);
      filename = `FocusFlow_Analytics_${new Date().toISOString().split('T')[0]}.csv`;
      mimeType = 'text/csv';
    } else {
      content = await exportAnalyticsReport(history);
      filename = `FocusFlow_Report_${new Date().toISOString().split('T')[0]}.txt`;
      mimeType = 'text/plain';
    }
    
    const fileUri = FileSystem.documentDirectory + filename;
    await FileSystem.writeAsStringAsync(fileUri, content);

    // Dynamically import expo-sharing at call-time to avoid requiring the native module
    // before the runtime is ready or in environments where it isn't available.
    let Sharing;
    try {
      Sharing = await import('expo-sharing');
    } catch (e) {
      console.log('expo-sharing not available:', e?.message || e);
      return { success: false, message: 'Sharing not available on this platform' };
    }

    if (Sharing?.isAvailableAsync && (await Sharing.isAvailableAsync())) {
      await Sharing.shareAsync(fileUri, {
        mimeType,
        dialogTitle: 'Share FocusFlow Analytics',
        UTI: format === 'csv' ? 'public.comma-separated-values-text' : 'public.plain-text',
      });
    } else {
      // Fallback for platforms without sharing
      console.log('Sharing not available');
      return { success: false, message: 'Sharing not available on this platform' };
    }
    
    return { success: true, filename };
  } catch (error) {
    console.error('Export failed:', error);
    return { success: false, message: error.message };
  }
}

export async function generateWeeklyDigest(history) {
  const summary = computeSummary(history);
  const thisWeekMinutes = summary.weekBuckets.reduce((a, b) => a + b, 0);
  const avgDaily = Math.round(thisWeekMinutes / 7);
  
  // Simple achievement detection
  const achievements = [];
  if (summary.bestStreakDays >= 7) achievements.push('🔥 Week-long focus streak!');
  if (thisWeekMinutes >= 300) achievements.push('⏰ 5+ hours this week!');
  if (summary.totalSessions >= 50) achievements.push('🎯 50+ total sessions!');
  if (avgDaily >= 60) achievements.push('📈 Averaging 1hr+ daily!');
  
  return {
    weekMinutes: thisWeekMinutes,
    avgDaily,
    changePercent: summary.changeVsLastWeekPercent,
    achievements,
    insight: `Your most productive day this week was ${['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][summary.productiveDayIndex]}.`
  };
}